name: Android Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Project
        run: ./gradlew assembleDebug
